# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [2]:
#todo: 
num = np.arange(10)
print(num)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [6]:
#todo:
num_zeros= np.zeros(5) #crea un arrya con 5 ceros
print(num_zeros)
num_zeros[2] = 5 #asigna el valor 5 a la posicion 2 del array
print(num_zeros)

[0. 0. 0. 0. 0.]
[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [8]:
#todo: 
matriz = np.random.rand(3,3) #crea una matriz de 3x3 con valores aleatorios entre 0 y 1
print(matriz)

[[0.87342106 0.2629053  0.48120764]
 [0.07395431 0.5138434  0.22148814]
 [0.00973284 0.13791051 0.63299447]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [12]:
#todo:
arr = np.array([10,20,30,40,50]) #crea un array con los valores 10,20,30,40,50
arr_suma = arr + 5 #suma 5 a cada elemento del array
print(arr_suma)

num_aleatorio = randint(1,10) #genera un numero aleatorio entre 1 y 10
arr_multi = arr * num_aleatorio #multiplica cada elemento del array por el numero aleatorio
print(arr_multi)

[15 25 35 45 55]
[100 200 300 400 500]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [13]:
#todo:
matriz = np.eye(4) #crea una matriz identidad de 4x4
print(matriz)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [14]:
#todo: 
array_par = np.arange(0,21,2) #crea un array con los numeros pares del 0 al 20
print(array_par)

#operaciones basicas
suma = array_par + 2 #suma 2 a cada elemento del array
resta = array_par - 2 #resta 2 a cada elemento del array
multiplicacion = array_par * 2 #multiplica cada elemento del array por 2
division = array_par / 2 #divide cada elemento del array por 2

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicacion:", multiplicacion)
print("Division:", division)


[ 0  2  4  6  8 10 12 14 16 18 20]
Suma: [ 2  4  6  8 10 12 14 16 18 20 22]
Resta: [-2  0  2  4  6  8 10 12 14 16 18]
Multiplicacion: [ 0  4  8 12 16 20 24 28 32 36 40]
Division: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
